
# ?????URL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Bigdata@123
    # ???????????????Spring Boot??????
    # driver-class-name: com.mysql.cj.jdbc.Driver

    # Spring Boot??????????Hikari??????????????
    hikari:
      maximum-pool-size: 5  # ?????????????10
      max-lifetime: 1800000  # ???????????1800000 ms?30???
      minimum-idle: 2       # ????????????10
  application:
    name: database

mybatis:
  mapper-locations: classpath:mappers/*.xml  # MyBatis??????
  type-aliases-package: cn.izualzhy.database.pojo  # MyBatis?????????@Alias??
  type-handlers-package: cn.izualzhy.database.typehandler  # ?? typeHandler ????

logging:
  level:
    root: INFO  # ????
    org:
#      springframework: DEBUG
      mybatis: DEBUG
server:
  port: 9001


