server:
  port: 3001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: custom-metrics
          uri: forward:/actuator/metrics
          predicates:
            - Path=/metrics
        - id: route-example
          uri: http://127.0.0.1:6001/user/routeExample
          predicates:
            - Path=/user/routeExample
        - id: add-request-header-example
          uri: http://127.0.0.1:6001/user/addRequestHeaderExample
          predicates:
            - Path=/user/addRequestHeaderExample
          filters:
            - AddRequestHeader=X-Request-red, blue

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
#    reactor.netty.http.server: DEBUG

dynamic-route:
  url-mapping: "{'pathA': 'http://localhost:8101', 'pathB': 'http://localhost:8102', 'pathC': 'http://localhost:8103', 'pathD': 'http://localhost:6001'}"
#  url-mapping: "{pathA: 'http://localhost:8101', pathB: 'http://localhost:8102', pathC: 'http://localhost:8103'}"

gateway:
  timeout-ms: 60000

management:
  endpoint:
    gateway:
      # 默认已开启
      enabled: true
  endpoints:
    web:
      # 默认只暴露了 health/info 端点
      exposure:
        include: "*"
