# ??????
server:
  port: 3001
# Spring?????????
spring:
  application:
    name: gateway


  cloud:
    gateway:
      # ??????
      routes:
        # ????
        - id: fund
          # ??URI
          uri: http://localhost:7001
          # ????
          predicates:
          - Path=/r4j/**